// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Stats struct {
	Language string  `json:"language"`
	Count    int     `json:"count"`
	Average  float64 `json:"average"`
}

type TestRun struct {
	Language     string `json:"language"`
	TimePerRunMs int    `json:"timePerRunMs"`
}
